server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: membership-service
          uri: lb://membership-service
          predicates:
            - Path=/api/members/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: lesson-service
          uri: lb://lesson-service
          predicates:
            - Path=/api/lessons/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

